port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
redis:
  address: municipal-redis:6379
keys:
  APImunic1palLK: secret_municipal_lk_2024
logging:
  level: info
