port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  node_ip: 127.0.0.1
redis:
  address: municipal-redis:6379
keys:
  APImunic1palLK: MSQ5qqV5LchTak6KR9n6F1iRTgEW8kszoFbr1ird
logging:
  level: info
